services:
  - type: web
    name: django-backend
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn your_project_name.wsgi"
    envVars:
      - key: DATABASE_URL
        fromDatabase: true
        name: postgres-db
      - key: PYTHON_VERSION
        value: "3.10"

databases:
  - name: postgres-db
    plan: free
